### ISSUE TITLE
In case of invalid JSON - please show path

### ISSUE THREAD

**Issue by vitaly-zdanevich** [CivilServiceUSA/minify-json#2]
Current exception looks like this:

```
undefined:88
    "button_logout": {
    ^

SyntaxError: Unexpected string in JSON at position 2980
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/minify-json/index.js:55:23
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
```

But I have many JSONs with such key.

**Comment by vitaly-zdanevich** [comment]
```
{
    "appDesc": {
        "message": "Intelligent Speaker: smart reader running on leading tts engine. Convert files news blog posts & more to speech Listen on any device",
        "description": "Max characters: 132"
    },
    "login": {
        "message": "LOGIN",
        "description": "For login screen"
    },
    "placeholder_search": {
        "message": "Search",
        "description": "Top bar, displayed inside input when no text entered; max chars: 20"
    },
    "noItems": {
        "message": "Start by adding web-pages to the feed",
        "description": "After installing on first opening user will see this text, max chars: 80"
    },

    "tooltip_addToFeed": {
        "message": "Click here to save this page to your list and listen to it later",
        "description": "Max characters: 70"
    },
        "contextMenu_addToFeed": {
            "message": "Add to feed"
        },
        "snackbar_addedToFeed": {
            "message": "Added to feed",
            "description": "Max characters: 40"
        },
        "snackbar_error_noTextHere": {
            "message": "No text on this page. Write to us if you disagree",
            "description": "Max characters: 60"
        },
        "snackbar_error_languageOfThePageIsUndefined": {
            "message": "Language of the page is undefined",
            "description": "Max characters: 40"
        },

    "availableTime": {
        "message": "Reading time left: ",
        "description": "Max characters: 20."
    },
    "button_podcastEmail": {
        "message": "Email podcast link",
        "description": "Max characters: 25"
    },
        "snackbar_podcastEmailSent": {
            "message": "Email with podcast link sent",
            "description": "Max characters: 50"
        },
        "snackbar_error_podcastEmail": {
            "message": "Error sending email with podcast link :(",
            "description": "Max characters: 50"
        },
    "button_feedback": {
        "message": "Give feedback",
        "description": "Button in the drawer menu. Max characters: 22"
    },
   "button_ideas": {
        "message": "Submit an idea",
        "description": "Button in the drawer menu. Max characters: 22"
    },
    "button_upgrade": {
        "message": "UPGRADE PLAN",
        "description": "Max characters: 25"
    },
    "button_accountPage": {
        "message": "Account",
        "description": "Button in the drawer menu. Max characters: 22"
    },
    "settings": {
        "message": "Settings",
        "description": "Button in the drawer menu. Max characters: 22"
    },
        "languageOfTheUI": {
            "message": "Language of the interface",
            "description": "Button in the settings menu. Max characters: 22"
        },
        "voice": {
            "message": "Voice",
            "description": "Button in the settings menu. Max characters: 22"
        },
        "breathing": {
            "message": "Breathing",
            "description": "Button in the settings menu. Max characters: 22"
        }
   "button_logout": {
        "message": "Logout",
        "description": "Button in the drawer menu. Max characters: 22"
    },

    "prevChunk": {
        "message": "Rewind back",
        "description": "Max characters: 15"
    },
    "playPause": {
        "message": "Play/Pause the list"
    },
    "nextChunk": {
        "message": "Fast forward",
        "description": "Max characters: 15"
    },
    "tooltip_continuousPlaying": {
        "message": "When infinity: plays all the feed items in your list, when 1: stops playing after one text",
        "description": "Max characters: 99"
    },
    "playbackRate": {
        "message": "Playback rate",
        "description": "Max characters: 20"
    },

    "delete": {
        "message": "Delete"
    },
        "button_cancel": {
            "message": "CANCEL",
            "description": "Yes please in UPPERCASE"
        },
        "snackbar_itemRemoved": {
            "message": "Item removed"
        },
        "snackbar_error_feedItemRemoving": {
            "message": "Error removing"
        },

    "msg_exhausted_title": {
        "message": "You have used all free time available for this month."
    },
    "msg_exhausted_body": {
        "message": "Thank you for being with Intelligent Speaker! Want more time? Subscribe to continue listening to your texts!"
    }
}
```
